# 5G Dataset 

##### BS has too many unique values using Target Encoding replaces each category with the mean of the target variable (Energy) for that category. 

##### This method allows the model to learn patterns related to the base station identifiers without creating a large number of features.


# Target Encoding
encoder = ce.TargetEncoder(cols=['BS'])
df['BS_encoded'] = encoder.fit_transform(df['BS'], df['Energy'])


In [5]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

#####

Processes 
- Target variable y = Energy 

- Spilt X and Y 

- BS = Target Encoding for BS Column 



In [7]:
df = pd.read_csv('5G_energy_consumption_dataset.csv')
df.head()

Time   BS     Energy      load  ESMODE   TXpower
0  20230101 010000  B_0  64.275037  0.487936     0.0  7.101719
1  20230101 020000  B_0  55.904335  0.344468     0.0  7.101719
2  20230101 030000  B_0  57.698057  0.193766     0.0  7.101719
3  20230101 040000  B_0  55.156951  0.222383     0.0  7.101719
4  20230101 050000  B_0  56.053812  0.175436     0.0  7.101719

In [71]:
df[['ESMODE']].value_counts()

ESMODE  
0.000000    87475
2.000000     1299
1.999722      226
0.002500      134
0.000556      122
            ...  
0.000456        1
1.992778        1
1.993611        1
0.000394        1
0.000300        1
Name: count, Length: 1713, dtype: int64

In [11]:
df.describe(include = "all")

Time     BS        Energy          load        ESMODE  \
count             92629  92629  92629.000000  92629.000000  92629.000000   
unique              168    923           NaN           NaN           NaN   
top     20230102 230000  B_583           NaN           NaN           NaN   
freq                766    130           NaN           NaN           NaN   
mean                NaN    NaN     28.138997      0.244705      0.081361   
std                 NaN    NaN     13.934645      0.234677      0.382317   
min                 NaN    NaN      0.747384      0.000000      0.000000   
25%                 NaN    NaN     18.236173      0.057370      0.000000   
50%                 NaN    NaN     24.065770      0.165550      0.000000   
75%                 NaN    NaN     35.724963      0.363766      0.000000   
max                 NaN    NaN    100.000000      0.993957      4.000000   

             TXpower  
count   92629.000000  
unique           NaN  
top              NaN  
freq             NaN  
mean        6.765427  
std         0.309929  
min         5.381166  
25%         6.427504  
50%         6.875934  
75%         6.875934  
max         8.375336

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92629 entries, 0 to 92628
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Time     92629 non-null  object 
 1   BS       92629 non-null  object 
 2   Energy   92629 non-null  float64
 3   load     92629 non-null  float64
 4   ESMODE   92629 non-null  float64
 5   TXpower  92629 non-null  float64
dtypes: float64(4), object(2)
memory usage: 4.2+ MB


In [15]:
df = df.drop("Time", axis=1)

In [17]:
print(df.head())

    BS     Energy      load  ESMODE   TXpower
0  B_0  64.275037  0.487936     0.0  7.101719
1  B_0  55.904335  0.344468     0.0  7.101719
2  B_0  57.698057  0.193766     0.0  7.101719
3  B_0  55.156951  0.222383     0.0  7.101719
4  B_0  56.053812  0.175436     0.0  7.101719


In [36]:
pip install category-encoders

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.0/82.0 kB 285.6 kB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [19]:
import category_encoders as ce

In [25]:
# Target Encoding
encoder = ce.TargetEncoder(cols=['BS'])
df['BS_encoded'] = encoder.fit_transform(df['BS'], df['Energy'])

In [23]:
print(df.head())

    BS     Energy      load  ESMODE   TXpower  BS_encoded
0  B_0  64.275037  0.487936     0.0  7.101719   73.087415
1  B_0  55.904335  0.344468     0.0  7.101719   73.087415
2  B_0  57.698057  0.193766     0.0  7.101719   73.087415
3  B_0  55.156951  0.222383     0.0  7.101719   73.087415
4  B_0  56.053812  0.175436     0.0  7.101719   73.087415


### Separate features and target variable

In [95]:
## Feature Selections

X = df[['load', 'TXpower', 'BS_encoded', 'ESMODE']]
y = df['Energy']

### Normalize the Data 

In [75]:
from sklearn.preprocessing import StandardScaler

In [97]:
X= preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[ 1.036457  ,  1.0850681 ,  3.51104077, -0.2128106 ],
       [ 0.42511173,  1.0850681 ,  3.51104077, -0.2128106 ],
       [-0.2170592 ,  1.0850681 ,  3.51104077, -0.2128106 ],
       [-0.09511653,  1.0850681 ,  3.51104077, -0.2128106 ],
       [-0.29516597,  1.0850681 ,  3.51104077, -0.2128106 ]])

### Split the Model into Training and Testing sets

In [79]:
from sklearn.model_selection import train_test_split  # To split the dataset into training and testing sets

In [101]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [103]:
X_train

array([[ 0.26221446,  0.35655964, -0.6117205 , -0.2128106 ],
       [ 0.12120704,  1.08241547,  1.18158068, -0.2128106 ],
       [-0.52474275, -1.09032905, -0.94136846, -0.2128106 ],
       ...,
       [ 0.79665335,  0.35655964, -0.54313128, -0.2128106 ],
       [-0.86108873,  1.08241547,  0.16639325, -0.2128106 ],
       [-0.33158285,  0.35655964, -0.34691553, -0.2128106 ]])

In [105]:
X_test

array([[ 0.54467915,  1.08241547,  1.39581727, -0.2128106 ],
       [-0.98461075,  0.35655964, -0.27649677,  4.7184008 ],
       [-0.70601392, -1.09032905, -1.13324505, -0.2128106 ],
       ...,
       [ 1.9524776 ,  0.35655964,  1.06916157, -0.2128106 ],
       [ 0.6815159 ,  0.35655964, -0.49779199, -0.2128106 ],
       [-0.95512329,  1.08241547,  1.03758703, -0.2128106 ]])

In [107]:
y_train

42091    13.751868
27803    44.394619
40368    15.994021
9254     25.859492
76007    42.002990
           ...    
6265     41.405082
54886    51.420030
76820    26.158445
860      30.642750
15795    21.524664
Name: Energy, Length: 74103, dtype: float64

In [109]:
y_test

65601    44.843049
2220     20.478326
54370    13.751868
80338    57.997010
32751    37.967115
           ...    
22459    35.426009
14808    21.375187
36465    40.956652
34944    24.813154
69268    30.493274
Name: Energy, Length: 18526, dtype: float64

In [119]:
pip install XGBoost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 22.5 kB/s eta 0:00:0000:0100:04m
Note: you may need to restart the kernel to use updated packages.


## Modelling 

## 1. Linear Regression 

In [111]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Initialize the model
linear_reg = LinearRegression()

# Fit the model to the training data
linear_reg.fit(X_train, y_train)

# Predict on the test data
y_pred_linear = linear_reg.predict(X_test)


In [113]:
# Evaluate the model
rmse_linear = np.sqrt(mean_squared_error(y_test, y_pred_linear))
r2_linear = r2_score(y_test, y_pred_linear)

print(f"Linear Regression:\n RMSE: {rmse_linear:.4f}\n R²: {r2_linear:.4f}\n")

Linear Regression:
 RMSE: 4.1687
 R²: 0.9084



## 2. Ridge Regression

In [117]:
from sklearn.linear_model import Ridge

# Initialize the model
ridge_reg = Ridge(alpha=1.0)

# Fit the model to the training data
ridge_reg.fit(X_train, y_train)

# Predict on the test data
y_pred_ridge = ridge_reg.predict(X_test)

# Evaluate the model
rmse_ridge = np.sqrt(mean_squared_error(y_test, y_pred_ridge))
r2_ridge = r2_score(y_test, y_pred_ridge)

print(f"Ridge Regression:\n RMSE: {rmse_ridge:.4f}\n R²: {r2_ridge:.4f}\n")

Ridge Regression:
 RMSE: 4.1687
 R²: 0.9084



## 3. Support Vector Regression (SVR)

In [121]:
from sklearn.svm import SVR

# Initialize the model
svr_reg = SVR(kernel='linear')

# Fit the model to the training data
svr_reg.fit(X_train, y_train)

# Predict on the test data
y_pred_svr = svr_reg.predict(X_test)

# Evaluate the model
rmse_svr = np.sqrt(mean_squared_error(y_test, y_pred_svr))
r2_svr = r2_score(y_test, y_pred_svr)

print(f"Support Vector Regression:\n RMSE: {rmse_svr:.4f}\n R²: {r2_svr:.4f}\n")

Support Vector Regression:
 RMSE: 4.2167
 R²: 0.9063



## 4. Gradient Boosting Regressor

In [123]:
from sklearn.ensemble import GradientBoostingRegressor

# Initialize the model
gb_reg = GradientBoostingRegressor()

# Fit the model to the training data
gb_reg.fit(X_train, y_train)

# Predict on the test data
y_pred_gb = gb_reg.predict(X_test)

# Evaluate the model
rmse_gb = np.sqrt(mean_squared_error(y_test, y_pred_gb))
r2_gb = r2_score(y_test, y_pred_gb)

print(f"Gradient Boosting Regressor:\n RMSE: {rmse_gb:.4f}\n R²: {r2_gb:.4f}\n")

Gradient Boosting Regressor:
 RMSE: 3.5302
 R²: 0.9343

